require "config.options"
require "config.plugins"
require "config.settings"
require "config.keymaps"
require "config.telescope"
require "config.autosave"
require "config.format"
require "config.rust"
