require("crates").setup {
  smart_insert = true,
  insert_closing_quote = true,
  avoid_prerelease = true,
  autoload = true,
  autoupdate = true,
  loading_indicator = true,
  date_format = "%d.%m.%y",
  popup = {
    autofocus = false,
    copy_register = '"',
    style = "minimal",
    border = "none",
    version_date = false,
    max_height = 30,
    min_width = 20,
    keys = {
      hide = { "q", "<esc>" },
      select = { "<cr>" },
      select_alt = { "s" },
      copy_version = { "yy" },
      toggle_feature = { "<cr>" },
      goto_feature = { "gd", "K" },
      jump_forward_feature = { "<c-i>" },
      jump_back_feature = { "<c-o>" },
    },
  },
  cmp = { insert_closing_quote = true },
}
